services:
  - type: web
    name: gameforge
    runtime: node
    nodeVersion: "18.18.0"
    buildCommand: npm install --build-from-source && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
